# Generated by Django 4.0.3 on 2022-06-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('pantone_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
    ]
