# Generated by Django 4.0.3 on 2022-06-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
    ]
