# Generated by Django 4.0.3 on 2022-06-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_remove_comments_style_remove_measurements_mc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('INI', 'Initial Comments'), ('GEN', 'General Comments'), ('FIT', 'Fit Comments'), ('SSC', 'Size Set Comments'), ('PPS', 'PP Sample Comments')], default='INI', max_length=3)),
                ('comments', models.TextField(help_text='Comments received from customer', verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.style')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
