# Generated by Django 4.0.3 on 2022-06-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_remove_comments_style_remove_measurements_mc_name_and_more'),
        ('product_colors', '0002_alter_colors_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity required')),
                ('color', models.ManyToManyField(to='product_colors.colors')),
                ('style_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.style')),
            ],
        ),
    ]
