# Generated by Django 4.0.3 on 2022-06-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_name', models.CharField(max_length=100, verbose_name='Measurement Chart')),
                ('description', models.CharField(default='measurement chart', help_text='eg: Mens Tshirt', max_length=200, verbose_name='Short description')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('measuringpoint', models.CharField(max_length=200)),
                ('tolerance', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('measurement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.measurementchart')),
            ],
        ),
    ]
