# Generated by Django 4.0.3 on 2022-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('useraccounts.user',),
        ),
        migrations.CreateModel(
            name='JUNIOREMP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('useraccounts.user',),
        ),
        migrations.CreateModel(
            name='MANAGER',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('useraccounts.user',),
        ),
        migrations.CreateModel(
            name='NEWUSER',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('useraccounts.user',),
        ),
        migrations.CreateModel(
            name='STOREKEEPER',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('useraccounts.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('NEWUSER', 'NewUser'), ('MANAGER', 'Manager'), ('CUSTOMER', 'Customer'), ('JUNIOREMP', 'JuniorEmp'), ('STOREKEEPER', 'Storekeeper')], default='NEWUSER', max_length=50, verbose_name='Type of user'),
        ),
    ]
