# Generated by Django 4.0.3 on 2022-04-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_customer_junioremp_manager_newuser_storekeeper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
