# Generated by Django 4.0.3 on 2022-05-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_delete_manager_merchandiser_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermore',
            name='user',
        ),
        migrations.AddField(
            model_name='customermore',
            name='customer',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.customer'),
            preserve_default=False,
        ),
    ]
