# Generated by Django 4.0.3 on 2022-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0007_remove_customermore_user_customermore_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMINUSER', 'AdminUser'), ('NEWUSER', 'NewUser'), ('MERCHANDISER', 'Merchandiser'), ('CUSTOMER', 'Customer'), ('JUNIOREMP', 'JuniorEmp'), ('STOREKEEPER', 'Storekeeper')], default='NEWUSER', help_text='User type/role - to be selected from the given list. This will determine the permissions. \nDefault value will be NEWUSER on registration.', max_length=50, verbose_name='Type of user'),
        ),
    ]
