# Generated by Django 4.0.3 on 2022-04-12 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Delivery date'),
        ),
        migrations.AddField(
            model_name='style',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity required'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='product_group',
            field=models.CharField(max_length=20, verbose_name='Product group'),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_description',
            field=models.TextField(max_length=100, verbose_name='Style description'),
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50, verbose_name='Accessories name')),
                ('purchase_units', models.CharField(max_length=10, verbose_name='Purchase units')),
                ('qty_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity per item')),
                ('style_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.style')),
                ('supplier', models.ManyToManyField(blank=True, null=True, to='suppliers.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Accessories name')),
                ('purchase_units', models.CharField(max_length=10, verbose_name='Purchase units')),
                ('qty_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity per item')),
                ('style_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.style')),
                ('supplier', models.ManyToManyField(blank=True, null=True, to='suppliers.suppliers')),
            ],
        ),
    ]
