# Generated by Django 4.0.3 on 2022-04-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_customermore'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_name', models.CharField(max_length=100, verbose_name='Measurement Chart')),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='merchandiser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.manager', verbose_name='Merchandiser name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessories',
            name='style_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='products.style'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='style_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='products.style'),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('measuringpoint', models.CharField(max_length=200)),
                ('tolerance', models.DecimalField(decimal_places=2, default=0.5, max_digits=2)),
                ('measurement', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('mc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measurementchart')),
            ],
        ),
    ]
