# Generated by Django 4.0.3 on 2022-04-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_customermore'),
        ('products', '0002_measurementchart_style_merchandiser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='useraccounts.customer', verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='style',
            name='merchandiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandiser', to='useraccounts.manager', verbose_name='Merchandiser name'),
        ),
    ]
