# Generated by Django 4.0.3 on 2022-04-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0002_style_delivery_date_style_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='supplier',
        ),
        migrations.AddField(
            model_name='accessories',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
        migrations.RemoveField(
            model_name='processes',
            name='supplier',
        ),
        migrations.AddField(
            model_name='processes',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
    ]
