# Generated by Django 4.0.3 on 2022-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_style_merchandiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='measurement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
