# Generated by Django 4.0.3 on 2022-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_measurements_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementchart',
            name='description',
            field=models.CharField(default='measurement chart', max_length=200, verbose_name='Short description, eg: Mens T Shirt'),
        ),
    ]
