# Generated by Django 4.0.3 on 2022-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_measurementchart_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementchart',
            name='description',
            field=models.CharField(default='measurement chart', help_text='eg: Mens Tshirt', max_length=200, verbose_name='Short description'),
        ),
    ]
