# Generated by Django 4.0.3 on 2022-04-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_style_options_style_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
