# Generated by Django 4.0.3 on 2022-04-27 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_accessories_options_alter_processes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='details_received_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
