# Generated by Django 4.0.3 on 2022-05-02 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessories',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='accessory_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessories',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessories',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processes',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processes',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='process_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processes',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processes',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity required'),
        ),
    ]
