# Generated by Django 4.0.3 on 2022-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_accessories_assigned_by_accessories_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('pantone_no', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='color',
            field=models.ManyToManyField(to='products.colors'),
        ),
    ]
