# Generated by Django 4.0.3 on 2022-05-30 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_remove_style_color_remove_style_quantity_stylecombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='assigned_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='assigned_to',
            field=models.ManyToManyField(related_name='accessory_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processes',
            name='assigned_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processes',
            name='assigned_to',
            field=models.ManyToManyField(related_name='process_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
