# Generated by Django 4.0.3 on 2022-05-31 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_alter_accessories_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='process_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processes',
            name='qty_per_item',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity per item'),
        ),
        migrations.AlterField(
            model_name='processes',
            name='task_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
