# Generated by Django 4.0.3 on 2022-05-31 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_alter_processes_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='accessory_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
