# Generated by Django 4.0.3 on 2022-06-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0001_initial'),
        ('product_seasons', '0001_initial'),
        ('products', '0020_alter_accessories_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='style',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='mc_name',
        ),
        migrations.RemoveField(
            model_name='processes',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='processes',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='processes',
            name='style_no',
        ),
        migrations.RemoveField(
            model_name='processes',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stylecombo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stylecombo',
            name='style_no',
        ),
        migrations.AlterField(
            model_name='style',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_groups.productgroup'),
        ),
        migrations.AlterField(
            model_name='style',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_seasons.season'),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='MeasurementChart',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.DeleteModel(
            name='Processes',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='StyleCombo',
        ),
    ]
